#!/usr/bin/env bash
# Recollect — render the EXTERNAL synthetic-probe target file from your deployment-unique domain.
#
# Turns on (or refreshes) the on-box EXTERNAL monitoring: it writes `external-targets/public-edge.yaml`
# — the Prometheus file-SD target list the `blackbox-https-external` job reads (see ../prometheus.yaml)
# — with the PUBLIC https URLs a real player hits, so Prometheus probes the full DNS → Cloudflare edge
# → (static SITE on Pages | GAME server through the Tunnel) path. The internal compose-network probes
# can't see those layers; this is what catches Tunnel-down / DNS-broken / TLS-expired.
#
# CONFIG HYGIENE: the domain is deployment-unique and NEVER committed. This script reads it at RUN
# TIME from the environment (or the box's .env) and writes a GITIGNORED file. The git tree keeps only
# the placeholder `public-edge.yaml.example`; no real host is ever committed. With no live file the
# external job + its alerts are inert (zero targets / noDataState: OK) — a clean clone and
# `make deploy-local` stay silent.
#
# USAGE (run it on the box, after the domain is known):
#   OBS_PUBLIC_DOMAIN=your-domain.com  deploy/compose/observability/prometheus/render-external-targets.sh
#   # optional overrides (defaults shown), matching the Pulumi `gameSubdomain` config:
#   OBS_PUBLIC_DOMAIN=your-domain.com  OBS_GAME_SUBDOMAIN=play  …/render-external-targets.sh
#
# DOMAIN SOURCE, in order: (1) $OBS_PUBLIC_DOMAIN, else (2) $OBS_GRAFANA_DOMAIN (the bare domain the
# deploy .env already carries — cloud-init writes it from the Pulumi `domain`), else (3) the
# OBS_GRAFANA_DOMAIN line of an .env passed as $1 or found at /opt/recollect/.env. If none yields a
# real domain, the script writes NOTHING and exits non-zero (it refuses to render a placeholder) — so
# it can never accidentally enable a bogus probe. To turn external monitoring OFF, delete the live
# file:  rm -f deploy/compose/observability/prometheus/external-targets/public-edge.yaml
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/external-targets/public-edge.yaml"

# Resolve the domain (see the header for the order). $1, if given, is an .env file to source the
# bare domain from (the box's OBS_GRAFANA_DOMAIN); otherwise try the well-known /opt/recollect/.env.
domain="${OBS_PUBLIC_DOMAIN:-${OBS_GRAFANA_DOMAIN:-}}"
if [ -z "$domain" ]; then
  ENV_FILE="${1:-/opt/recollect/.env}"
  if [ -f "$ENV_FILE" ]; then
    # Read ONLY the OBS_GRAFANA_DOMAIN key — don't source the whole secrets file.
    domain="$(sed -n 's/^OBS_GRAFANA_DOMAIN=//p' "$ENV_FILE" | tail -n1)"
  fi
fi

if [ -z "$domain" ] || [ "$domain" = "your-domain.com" ]; then
  echo "render-external-targets: no real domain set (OBS_PUBLIC_DOMAIN / OBS_GRAFANA_DOMAIN / .env)." >&2
  echo "  External monitoring stays OFF. Set OBS_PUBLIC_DOMAIN=your-domain.com and re-run." >&2
  exit 1
fi

game_sub="${OBS_GAME_SUBDOMAIN:-play}"   # play.<domain> — matches the Pulumi `gameSubdomain` default

# Write the live target list. Header marks it generated + gitignored so no one commits it by hand.
cat > "$OUT" <<YAML
# GENERATED by render-external-targets.sh — do NOT commit (gitignored). Live external-probe targets
# for the blackbox-https-external job. Re-run the script to refresh; delete this file to turn the
# external probes OFF. Source domain: ${domain}
- targets:
    - https://${domain}/
    - https://www.${domain}/
  labels:
    probe: public-site
- targets:
    - https://${game_sub}.${domain}/healthz
  labels:
    probe: public-game
YAML

echo "render-external-targets: wrote $OUT for domain '${domain}' (site apex/www + ${game_sub}.${domain}/healthz)."
echo "  Prometheus hot-reloads file-SD within the job's refresh_interval (5m); no restart needed."
