//! UniFFI bindings over `recollect-core`, so native iOS/Android shells
//! drive the exact same deterministic engine the server and web do.
//!
//! Design: JSON across the FFI boundary, mirroring the wasm `LocalGame` — a
//! `Game` handle plus a few string-returning methods, so the generated Swift /
//! Kotlin surface is tiny and the rules stay entirely in the core (the FFI layer
//! is a thin adapter, never a second rules implementation). The bindings are
//! generated by `uniffi-bindgen generate --library <cdylib>`.
#![deny(rustdoc::broken_intra_doc_links)]
#![deny(unsafe_code)] // forbid would break the uniffi macro expansion

use std::sync::Mutex;

uniffi::setup_scaffolding!();

/// The wire protocol version this build speaks (matches the server/web).
#[uniffi::export]
pub fn protocol_version() -> u16 {
    recollect_protocol::PROTOCOL_VERSION
}

/// The whole card catalog as JSON (every card keyed by id) — a complete card
/// database for a native shell to render, with no running game. Same shape the
/// web's `catalog_json` emits.
#[uniffi::export]
pub fn catalog_json() -> String {
    let cards: Vec<serde_json::Value> = recollect_core::cards::canon_catalog()
        .iter()
        .map(|c| {
            let mut kw: Vec<&str> = Vec::new();
            if c.arcane {
                kw.push("Arcane");
            }
            if c.warded {
                kw.push("Warded");
            }
            if c.mobile {
                kw.push("Mobile");
            }
            if c.steadfast {
                kw.push("Steadfast");
            }
            if c.relentless {
                kw.push("Relentless");
            }
            if c.lurk {
                kw.push("Lurk");
            }
            serde_json::json!({
                "id": c.id.0,
                "name": c.name,
                "kind": format!("{:?}", c.kind),
                "resonance": format!("{:?}", c.resonance),
                "cost": c.cost,
                "attack": c.attack,
                "defense": c.defense,
                "hp": c.hp,
                "keywords": kw,
                "rules": c.rules,
                "reach": format!("{:?}", c.reach),
            })
        })
        .collect();
    serde_json::to_string(&cards).unwrap()
}

/// A local game handle for a native shell: an in-process engine (vs the AI),
/// driven through JSON. The engine sits behind a `Mutex` because UniFFI objects
/// expose `&self` methods across the FFI boundary.
#[derive(uniffi::Object)]
pub struct Game {
    inner: Mutex<Inner>,
}

struct Inner {
    engine: recollect_core::Engine,
    ai: recollect_core::rng::Rng,
    difficulty: recollect_bot::Difficulty,
}

#[uniffi::export]
impl Game {
    /// A new vs-AI quick game (you are Seat A), reproducible from `seed`.
    #[uniffi::constructor]
    pub fn new(seed: u64) -> std::sync::Arc<Game> {
        let cat = recollect_core::cards::canon_catalog();
        let offers = recollect_core::quickplay::offer(seed);
        let deck_a = recollect_core::quickplay::generate_deck(offers[0].id, seed, &cat);
        let deck_b =
            recollect_core::quickplay::generate_deck(offers[1].id, seed.wrapping_add(1), &cat);
        let (engine, _) = recollect_core::Engine::new(seed, cat, deck_a, deck_b);
        std::sync::Arc::new(Game {
            inner: Mutex::new(Inner {
                engine,
                ai: recollect_core::rng::Rng::from_seed(seed ^ 0xA1),
                difficulty: recollect_bot::Difficulty::Normal,
            }),
        })
    }

    /// The acting seat's redacted `PlayerView` as JSON.
    pub fn view_json(&self) -> String {
        let g = self.inner.lock().unwrap();
        let seat = g.engine.state().active;
        serde_json::to_string(&recollect_core::view::view_for(&g.engine, seat)).unwrap()
    }

    /// Every legal move for the acting seat, labeled, as JSON `[{label, cmd}]`
    /// (the same menu the CLI/web render).
    pub fn legal_json(&self) -> String {
        let g = self.inner.lock().unwrap();
        let seat = g.engine.state().active;
        let moves: Vec<serde_json::Value> = g
            .engine
            .legal_commands(seat)
            .into_iter()
            .map(|cmd| {
                serde_json::json!({
                    "label": recollect_protocol::label(&g.engine, seat, &cmd),
                    "cmd": cmd,
                })
            })
            .collect();
        serde_json::to_string(&moves).unwrap()
    }

    /// Apply a `Command` (JSON) for the acting seat. Returns the events as JSON,
    /// or `{"reject": …}`. Malformed JSON rejects rather than panicking.
    pub fn apply_json(&self, command_json: String) -> String {
        let mut g = self.inner.lock().unwrap();
        let Ok(cmd) = serde_json::from_str::<recollect_core::state::Command>(&command_json) else {
            return "{\"reject\":\"Malformed\"}".to_string();
        };
        let seat = g.engine.state().active;
        match g.engine.apply(seat, cmd) {
            Ok(evs) => serde_json::to_string(&evs).unwrap(),
            Err(r) => serde_json::json!({ "reject": format!("{r:?}") }).to_string(),
        }
    }

    /// Let the AI take Seat B's turn (call after the human ends theirs).
    pub fn ai_take_turn(&self) -> String {
        let mut g = self.inner.lock().unwrap();
        let seat = g.engine.state().active;
        let Inner {
            engine,
            ai,
            difficulty,
        } = &mut *g;
        let cmd = recollect_bot::choose(engine, seat, *difficulty, ai);
        match engine.apply(seat, cmd) {
            Ok(evs) => serde_json::to_string(&evs).unwrap(),
            Err(r) => serde_json::json!({ "reject": format!("{r:?}") }).to_string(),
        }
    }

    /// Whose turn it is (`"A"`/`"B"`).
    pub fn active_seat(&self) -> String {
        format!("{:?}", self.inner.lock().unwrap().engine.state().active)
    }

    /// True once the telling has ended.
    pub fn is_over(&self) -> bool {
        matches!(
            self.inner.lock().unwrap().engine.state().phase,
            recollect_core::state::Phase::Finished { .. }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_ffi_game_plays_through_json() {
        // The binding surface drives a real game: views + legal moves are JSON,
        // commands apply, and the AI answers — all over the same shape Swift/Kotlin
        // will call. (Compiles + runs on the host; bindgen generates the bindings.)
        assert!(protocol_version() >= 1);
        let cat: Vec<serde_json::Value> = serde_json::from_str(&catalog_json()).unwrap();
        assert!(cat.len() > 100, "the catalog is exported");

        let g = Game::new(7);
        assert_eq!(g.active_seat(), "A");
        let view: serde_json::Value = serde_json::from_str(&g.view_json()).unwrap();
        assert_eq!(view["seat"], "A");
        let legal: Vec<serde_json::Value> = serde_json::from_str(&g.legal_json()).unwrap();
        assert!(!legal.is_empty(), "the opening has legal moves");

        // Apply the first legal move, then let the AI reply — no panics.
        let cmd = legal[0]["cmd"].clone();
        let out = g.apply_json(serde_json::to_string(&cmd).unwrap());
        assert!(!out.contains("reject"), "a legal move applies: {out}");
        if !g.is_over() && g.active_seat() == "B" {
            g.ai_take_turn();
        }
    }
}
